USE FIRST;

SET TRANSACTION ISOLATION LEVEL
READ COMMITTED;
BEGIN;
SELECT *
FROM Пользователь
WHERE АдресПочты LIKE '%@mail.ru' LOCK
IN SHARE MODE;

SELECT SLEEP(10);


UPDATE Пользователь
SET Пароль = NULL
WHERE АдресПочты LIKE '%@mail.ru';